import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { Toaster } from "react-hot-toast";

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["100", "400", "700"],
  variable: "--font-raleway",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "400", "700"],
  variable: "--font-poppins", // Make sure the variable is set
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <>
          <body
            className={`${poppins.variable} ${raleway.variable} antialiased`} // Add poppins variable here
          >
            <div className="absolute w-full">
              <div className="fixed top-0 w-full h-fit z-10">
                <Navbar />
              </div>

              <div className="relative top-14 ">
                {children}
                <Toaster position="top-right" />
              </div>
            </div>
          </body>
        </>
      </UserProvider>
    </html>
  );
}
